### PR TITLE
Add helper function for sanitizing integer field of mixed input

### PR DESCRIPTION
**Pull request by davisshaver**

### CODE REVIEW

**Comment by dlh01** [comment]
I admit, I haven't seen something like this before. What's the issue? Is it related to the discussion here? https://github.com/alleyinteractive/wordpress-fieldmanager/pull/617

**Comment by davisshaver** [comment]
@dlh01 We need to specify a callback in WP SEO Social for images, so I just made sure we also used it when sanitizing the settings image integers.

**Comment by dlh01** [comment]
OK. I have a more formal branch for `register_meta()` in the works. I'll merge this branch into mine and submit a PR for it shortly.

**Comment by dlh01** [comment]
Sorry that we didn't get around to this one. All PRs that aren't fixing bugs are now being closed, as there are no plans for additional feature development for WP SEO.

**Pull request closed without merging**
