### PR TITLE
Fix social changes

### PR DESCRIPTION
**Pull request by davisshaver**
Follows up https://github.com/alleyinteractive/wp-seo/pull/63

Supported by https://github.com/alleyinteractive/wp-seo-social/pull/2

### CODE REVIEW

**Comment by dlh01** [comment]
Heads-up that the target branch will need to be `0.13.0`.

**Comment by davisshaver** [comment]
@dlh01 Thanks, I'm just running it against master for the CI. This branch is based on on `0.13.0` though.

**Comment by dlh01** [comment]
Ah ha. Maybe we should have Travis also run against the latest "release" branch for convenience.

**Comment by davisshaver** [comment]
@dlh01 I'm game... and not to blow up this thread, but I did want to continue the conversation you raised in https://github.com/alleyinteractive/wp-seo/pull/63#issuecomment-274351919 somewhere. My bad that it took a few weeks to come back to this.

I've tried to incorporate as much of your feedback as possible. The big point I didn't want to tackle in code yet was data structure. What downsides have you run into with the existing approach? 

Another point was get_key/WP_Query. I don't think we need this unless we revisit the options structure to be more complex. But right now using the `is_home()` style conditionals seems to map our content model well.

I also lean towards including the extra fields to keep the library useful for expansion but I see the argument to not include at this point too.

**Comment by dlh01** [comment]
> The big point I didn't want to tackle in code yet was data structure. What downsides have you run into with the existing approach?

My biggest concern is that if you have a taxonomy and a post type with the same name, one will overwrite the other in the option array.

My other reasons are more like gripes than downsides. For example, the `archive_` and `single_[whatever]` array key names are made up for just this plugin (hence the need for a special function to just get the prefix), and I wish now I had tried to find a naming structure that exists in core.

> Another point was get_key/WP_Query. I don't think we need this unless we revisit the options structure to be more complex. But right now using the is_home() style conditionals seems to map our content model well.

I'm not sure we disagree, or maybe I'm misunderstanding you or was unclear originally. I just meant that we would check `$query->is_home()` instead of `is_home()`. I think requiring a `WP_Query` would make the function more reusable in contexts without a main query, like unit tests or the REST API.

> I also lean towards including the extra fields to keep the library useful for expansion but I see the argument to not include at this point too.

I'm also on the fence, but I'm cool with following your lead either way.

**Comment by davisshaver** [comment]
@dlh01 My apologies, I missed this comment when it was posted.

-  I'm not seeing the conflict potential for taxonomies and post types with the same name. I also created matching taxonomy and post type locally to try that way. could you point me to where you see this conflict?

- Re the array keys, the naming structure in `WP_SEO()->get_key()` seems to be in Core via template structure. 

- Just added a $query param to the get_key function.

**Comment by davisshaver** [comment]
Updated to pass CI on PHP 7.

**Comment by dlh01** [comment]
> I'm not seeing the conflict potential for taxonomies and post types with the same name. I also created matching taxonomy and post type locally to try that way. could you point me to where you see this conflict?

To replicate, the post type and taxonomy need to share a `name`, and the post type needs to have `has_archive => true`. When that happens, they share the same `archive_*` keys: https://github.com/alleyinteractive/wp-seo/blob/master/php/class-wp-seo-settings.php#L293-L311.

**Comment by dlh01** [comment]
@davisshaver I filed a few issues and PRs with post-hoc ideas and questions for discussion that I'd be keen to get your thoughts about if you have time. I put them in the 0.13.0 milestone just so they were distinguishable, but I know we've been working on the 0.13.0 branch for a while, so I'll also be interested in how much more chatter you think it can handle.

**Pull request merged**
